### ISSUE TITLE
About Us - manager image

### ISSUE THREAD

**Issue by kimcartwright** [dcartwright07/hec-theme-eyecare#1]
link: http://hamiltoneyecarecenter.com/our-team/
![Screen Shot 2019-10-30 at 11 26 25 AM](https://user-images.githubusercontent.com/57187436/67872312-2c1e3c80-fb08-11e9-8be9-23cdd348edb0.png)

`figure.content-image` is set to `max-height: 190px` which is cutting off the image.  (figure.content-image is being used for something on the home page)  I'd like to have the full image showing.

**Comment by dcartwright07** [comment]
The issue is resolved. The `max-height: 190px` is now only applied to the images on the home page.
