### ISSUE TITLE
Mobile: Doctor profile page

### ISSUE THREAD

**Issue by kimcartwright** [dcartwright07/hec-theme-eyecare#11]
On the individual doctor's profile pages, when in mobile view, the image should be centered at top, but it's still left aligned.  I will "duplicate"/edit the content and do "show-for large"/"hide-for-large" in order for the picture to be centered in mobile view.

**Comment by kimcartwright** [comment]
Actually, I assume I could do that (as mentioned above), but I can't.  These pages are automatically created from the information entered in the "optometrists" profiles.  Not sure how to edit the layout in mobile view only.

**Comment by dcartwright07** [comment]
Add a `text-align: center` to the class that enclosed the image.
