### ISSUE TITLE
Mobile: Technology page - images

### ISSUE THREAD

**Issue by kimcartwright** [dcartwright07/hec-theme-eyecare#5]
The images on the technology page are not showing up in the mobile version.

**Comment by dcartwright07** [comment]
Duplicate content and change the template structure. Add class to "Extra Row Classes" `hide-for-large`.

**Comment by dcartwright07** [comment]
Images were using the URL that include the _hamiltoneyecarecenter.com_ instead of _hamiltoneyecare.biz_. We will probably have to readjust these when the site goes live.
